# Generated by Django 4.2.4 on 2023-09-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezapp', '0002_customuser_uutoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='loginToken',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
